version: "3"
services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'

    ports:
    - 27017-27019:27017-27019
    # command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: testDB

    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  app:
    image: private.registry.io/mongo-comsumer:latest
    ports:
    - 8080:8080
    links:
    - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
volumes: 
  mongodb_data:
    driver: local
