version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
    environment:
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=abstract
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=testDB
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  app:
    image: private.registry.io/mongo-comsumer:latest
    ports:
    - 8080:8080
    links:
    - mongodb

volumes: 
  mongodb_data:
    driver: local
